### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by insurgencless** [Cramber25/roblox2fapayout#1]
Hey im new to python can you show me a me a example of removing Authenticator App im trying to modify the script so it does that but im not able to

**Comment by Cramber25** [comment]
> Hey im new to python can you show me a me a example of removing Authenticator App im trying to modify the script so it does that but im not able to

what do you mean by "removing Authenticator App"?

**Comment by insurgencless** [comment]
![Screenshot 2024-06-07 132713](https://github.com/Cramber25/roblox2fapayout/assets/126472818/eddd83a4-80ad-4560-acd5-e31515474b53)
The 2 Step Verification or show a example of something else that requires https://apis.roblox.com/challenge/v1/continue I'm so lost on how that api works since it seems roblox updated there apis

**Comment by Cramber25** [comment]
this repository has a readme containing all the instructions and explanations on how to validate a request. it should work on any other endpoints that require 2fa. im not exactly sure what else requires a 2 factor authentication on roblox

**Comment by Cramber25** [comment]
insurgencless contacted me on discord and we solved the issue
