### ISSUE TITLE
Do we need to input 2FA six digit code every time?

### ISSUE THREAD

**Issue by sounak9725** [Cramber25/roblox2fapayout#2]
# two factor secret to generate the 6 digit 2fa code
twofactor_secret=""
 From where will I get it what are the steps to get it? I am using google authenticator by the way.

**Comment by Cramber25** [comment]
Response to the title: No, the code I provided generates the 2FA 6-digit code automatically. However, if you prefer, you can enter it manually.

The **twofactor_secret** is the key/secret used to generate the 6-digit code. This secret is provided to you when setting up 2FA authentication on Roblox, usually via a QR code. During setup, you can also press a button to reveal the secret itself, allowing you to copy it. While I don’t use Google Authenticator, most 2FA apps allow you to edit an entry and copy the secret from there without the need of setting up the 2FA authentication again.

I hope this helps.
