### ISSUE TITLE
KeyError: 'x-csrf-token'

### ISSUE THREAD

**Issue by sounak9725** [Cramber25/roblox2fapayout#3]
![Screenshot 2024-08-24 130748](https://github.com/user-attachments/assets/ca2abd80-0a93-434c-8ac6-e7cf9373e26b)

**Comment by sounak9725** [comment]
Using your code as it is. It was working 10 hours ago. It was working very much fine but in the morning idk what happened.

**Comment by sounak9725** [comment]
![image](https://github.com/user-attachments/assets/130c7431-0af8-41c8-9e61-6585832f7f55)

New error now.

**Comment by Cramber25** [comment]
Thank you for reporting this issue, I can replicate this error on my computer which propably means roblox changed how their 2fa system works, I'm going to check it and update the repository soon

**Comment by Cramber25** [comment]
okay, i just updated the main.py file with the new method

**Comment by sounak9725** [comment]
Alright, I will try and if any errors I will post it here.

**Comment by sounak9725** [comment]
Hi, it's working fine. Thank you so much. You now may close the issue. Have a good day.
